eventeam/applications/users/urls.py
from django.urls import path

from . import views
from .views import ResetPasswordView
from django.contrib.auth import views as auth_views
app_name = "users_app"


urlpatterns = [
    path(
        'registrar/',
        views.UserRegisterView.as_view(),
        name='user-register'),
    path(
        'login/',
        views.LoginUser.as_view(),
        name='user-login'),
    path(
        'logout/',
        views.LogoutView.as_view(),
        name='user-logout'),
    path(
        'registrar-propietario/',
        views.PropietarioRegister.as_view(),
        name='registrar-propietario'),
    path(
        'password-reset/',
         ResetPasswordView.as_view(),
        name='password_reset'),

]

eventeam/eventeam/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.salones.urls')),
    re_path('', include('applications.users.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventeam/applications/users/models.py
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
#
from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    GENDER_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Femenino'),
        ('O', 'Otros'),
    )

    class Type(models.IntegerChoices):
        SUPER_ADMIN = (0, 'Super Admin')
        USER = (1, 'user')
        CLIENT = (2, 'Client')

    type = models.IntegerField(verbose_name='Type', choices=Type.choices)
    first_name = models.CharField(verbose_name='Nombre', max_length=100)
    last_name = models.CharField(verbose_name='Apellidos', max_length=100)
    region = models.CharField(verbose_name='Region', max_length=50)
    city = models.CharField(verbose_name='Ciudad', max_length=50)
    phone = models.CharField(verbose_name='Celular', max_length=20)
    email = models.EmailField(verbose_name='Email', unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = UserManager()

    def get_short_name(self):
        return self.email

    def get_full_name(self):
        return '%s %s' % (self.first_name, self.last_name)

eventeam/applications/users/forms.py
from captcha.fields import ReCaptchaField
from django import forms
from django.contrib.auth import authenticate
from .models import User


class UserRegisterForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = visible.field.label

    password = forms.CharField(
        label='Contrasena',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contrasena'
            }
        )
    )
    captcha = ReCaptchaField()

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
            'region',
            'city',
            'phone'
        )


class LoginForm(forms.Form):
    email = forms.EmailField(
        label='email',
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'email',
            }
        )
    )
    password = forms.CharField(
        label='Contrasena',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Contrasena'
            }
        )
    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        username = self.cleaned_data['email']
        password = self.cleaned_data['password']
        if not authenticate(username=username, password=password):
            raise forms.ValidationError('Los datos del usuario no son correctos')

        return self.cleaned_data

eventeam/applications/users/views.py
from django.contrib.auth import logout, authenticate, login
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import TemplateView, FormView
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from .forms import UserRegisterForm, LoginForm
from .models import User


# Create your views here.
class RegistrarUsuario(TemplateView):
    template_name = 'users/registrar.html'


class UserRegisterView(FormView):
    template_name = 'users/registrar.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('users_app:user-login')

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('/')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        #
        User.objects.create_user(
            form.cleaned_data['email'],
            form.cleaned_data['password1'],
            first_name=form.cleaned_data['first_name'],
            last_name=form.cleaned_data['last_name'],
            region=form.cleaned_data['region'],
            city=form.cleaned_data['city'],
            phone=form.cleaned_data['phone']
        )
        # enviar el codigo al email del user
        return super(UserRegisterView, self).form_valid(form)


class LoginUser(FormView):
    template_name = 'users/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('home_app:inicio')

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('/')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = authenticate(
            username=form.cleaned_data['email'],
            password=form.cleaned_data['password']
        )
        login(self.request, user)
        return super(LoginUser, self).form_valid(form)


class LogoutView(View):

    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(
            reverse('users_app:user-login')
        )


class PropietarioRegister(FormView):
    template_name = 'users/registrar-propietario.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('users_app:user-login')

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('/')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        User.objects.create_propietario(
            form.cleaned_data['email'],
            form.cleaned_data['password1'],
            first_name=form.cleaned_data['first_name'],
            last_name=form.cleaned_data['last_name'],
            region=form.cleaned_data['region'],
            city=form.cleaned_data['city'],
            phone=form.cleaned_data['phone']
        )

        return super(PropietarioRegister, self).form_valid(form)


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    subject_template_name = 'users/subject/password_reset_subject.txt'
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."

    success_url = reverse_lazy('home_app:inicio')

eventeam/templates/users/login.html
{% extends 'base.html' %}
{% block title %}
    Salones de eventos
{% endblock title%}
{% block content %}
{% include 'includes/header.html' %}
    <section class="vh-100 gradient-custom mb-5">
        <div class="container py-5 h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
              <div class="card text-white" style="border-radius: 1rem;
              background: linear-gradient(to bottom, rgba(255, 87, 9, 0.8) 0%, rgb(241, 82, 8) 100%);">
                <div class="card-body p-5 text-center">
      
                  <div class="mb-md-5 mt-md-4 pb-5">
      
                    <h2 class="fw-bold mb-2 text-uppercase">Inicia sesión</h2>
                    <p class="text-white-50 mb-5">Coloca tu correo y contraseña</p>
                    <form method="POST">{% csrf_token %}
                    <div class="form-outline form-white mb-4">
                      {{form.email}}
                      <label class="form-label" for="typeEmailX">Correo Electrónico</label>
                    </div>
      
                    <div class="form-outline form-white mb-4">
                      {{form.password}}
                      <label class="form-label" for="typePasswordX">Contraseña</label>
                    </div>
      
                    <p class="small mb-5 pb-lg-2"><a class="text-white" href="{% url 'users_app:password_reset' %}">¿Olvidaste tu contraseña?</a></p>
      
                    <button class="btn btn-outline-light btn-lg px-5" type="submit">Iniciar sesión</button>
                </form>
      
                  <div class="mt-3">
                    <p class="mb-0">¿No tienes una cuenta? <a href="{% url 'users_app:user-register'%}" class="text-white-50 fw-bold">Registrarse</a>
                    </p>
                  </div>
      
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    {% include 'includes/footer.html' %}
{% endblock content %}

eventeam/templates/users/password_reset.html
{% extends 'base.html' %}
{% block title %}
    Salones de eventos
{% endblock title%}
{% block content %}
{% include 'includes/header.html' %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                            <div id="error_div"></div>
                          <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                      <label class="small mb-1" for="id_email">Email</label>
                                        <input type="email" name="email"  class="form-control"
                                               autocomplete="email" maxlength="254" required id="id_email"
                                               placeholder="Enter email">
                                    </div>
                                </div>
                            </div>
                                <div class="form-row">
                                  <div class="col-md-10 offset-md-1">
                                    <div class="form-group mt-0 mb-1">
                                        <button type="submit" class="col-md-12 btn btn-dark">Submit
                                        </button>
                                    </div>
                                 </div>
                               </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

  </div>
    {% include 'includes/footer.html' %}
{% endblock content %}

eventeam/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block title %}
    Salones de eventos
{% endblock title%}
{% block content %}
{% include 'includes/header.html' %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info">
                        Tú contraseña ha sido cambiada. Puedes dirigirte a: <a href="{% url 'users_app:user-login' %}">Inicia sesión</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include 'includes/footer.html' %}
{% endblock content %}

eventeam/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% block title %}
    Salones de eventos
{% endblock title%}
{% block content %}
{% include 'includes/header.html' %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    {% if validlink %}
                        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                            <div class="card-header justify-content-center">
                              <h3 class="font-weight-light my-4 text-center">Reset Your Password</h3>
                            </div>
                            {% if form.errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <div id="form_errors">
                                        {% for key, value in form.errors.items %}
                                            <strong>{{ value }}</strong>
                                        {% endfor %}
                                    </div>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endif %}

                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password1">New Password</label>
                                                <input type="password" name="new_password1" autocomplete="new-password"
                                                       class="form-control" required id="id_new_password1"
                                                       placeholder="Enter password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password2">New Password Confirmation</label>
                                                <input type="password" name="new_password2" autocomplete="new-password"
                                                       required id="id_new_password2" class="form-control"
                                                       placeholder="Confirm password"/>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group mt-0 mb-1">
                                                <button type="submit" class="col-md-12 btn btn-dark" id="reset">Reset Password</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    {% else %}
                    <div class="alert alert-warning">
                        El link para cambiar la contraseña ha sido invalidado, posiblemente porque ya ha sido usado.
                        Por favor vuele a solicitar un cambio de contraseña.
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% include 'includes/footer.html' %}
{% endblock content %}

eventeam/templates/users/password_reset_email.html
{% autoescape off %}
  Para realizar el cambio de contraseña para tu email {{ user.email }} Eventeam App Account,
  clic en el enlace de abajo:

  {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

  Si el enlace no funciona, por favor copia y pega el link en tu navegador.

  Eventeam
{% endautoescape %}

eventeam/templates/users/registrar-propietario.html
{% extends 'base.html' %}
{% block title %}
    Salones de eventos
{% endblock title%}
{% block content %}
{% include 'includes/header.html' %}
<section class=" text-center text-lg-start">
    <style>
        .rounded-t-5 {
            border-top-left-radius: 0.5rem;
            border-top-right-radius: 0.5rem;
        }

        @media (min-width: 992px) {
            .rounded-tr-lg-0 {
                border-top-right-radius: 0;
            }

            .rounded-bl-lg-5 {
                border-bottom-left-radius: 0.5rem;
            }
        }
    </style>
    <div class="card mb-3">
        <div class="row g-0 d-flex align-items-center">
            <div class="col-lg-4 d-none d-lg-flex">
                <img src="https://mdbootstrap.com/img/new/ecommerce/vertical/004.jpg" alt="Trendy Pants and Shoes"
                     class="w-100 rounded-t-5 rounded-tr-lg-0 rounded-bl-lg-5"/>
            </div>
            <div class="col-lg-8">
                <div class="card-body py-5 px-md-5">

                    <form class="row g-3"> {% csrf_token %}
                        <div class="col-md-6">
                            <label for="inputEmail4" class="form-label">Nombre</label>
                            {{form.first_name}}
                        </div>
                        <div class="col-md-6">
                            <label for="inputPassword4" class="form-label">Apellidos</label>
                            {{form.last_name}}
                        </div>
                        <div class="col-md-6">
                            <label for="inputAddress" class="form-label">Email</label>
                            {{form.email}}
                        </div>
                        <div class="col-md-6">
                            <label for="inputAddress2" class="form-label">Region o Estado</label>
                            {{form.region}}
                        </div>
                        <div class="col-md-4">
                            <label for="inputCity" class="form-label">City</label>
                            {{form.city}}
                        </div>
                        <div class="col-md-4">
                            <label for="inputState" class="form-label">Celular</label>
                            {{form.phone}}
                        </div>
                        <div class="col-md-4">
                            <label for="inputZip" class="form-label">Contrasena</label>
                            {{form.password}}
                        </div>
                        <div class="col-12">
                            {{form.captcha}}
                        </div>
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary">Registrarse</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</section>
    {% include 'includes/footer.html' %}
{% endblock content %}

eventeam/templates/users/registrar.html
{% extends 'base.html' %}
{% block title %}
Salones de eventos
{% endblock title%}
{% block content %}
{% include 'includes/header.html' %}
<section class=" text-center text-lg-start">
    <style>
        .rounded-t-5 {
            border-top-left-radius: 0.5rem;
            border-top-right-radius: 0.5rem;
        }

        @media (min-width: 992px) {
            .rounded-tr-lg-0 {
                border-top-right-radius: 0;
            }

            .rounded-bl-lg-5 {
                border-bottom-left-radius: 0.5rem;
            }
        }
    </style>
    <div class="card mb-3">
        <div class="row g-0 d-flex align-items-center">
            <div class="col-lg-4 d-none d-lg-flex">
                <img src="https://mdbootstrap.com/img/new/ecommerce/vertical/004.jpg" alt="Trendy Pants and Shoes"
                     class="w-100 rounded-t-5 rounded-tr-lg-0 rounded-bl-lg-5"/>
            </div>
            <div class="col-lg-8">
                <div class="card-body py-5 px-md-5">

                    <form class="row g-3"> {% csrf_token %}
                        <div class="col-md-6">
                            <label for="inputEmail4" class="form-label">Nombre</label>
                            {{form.first_name}}
                        </div>
                        <div class="col-md-6">
                            <label for="inputPassword4" class="form-label">Apellidos</label>
                            {{form.last_name}}
                        </div>
                        <div class="col-md-6">
                            <label for="inputAddress" class="form-label">Email</label>
                            {{form.email}}
                        </div>
                        <div class="col-md-6">
                            <label for="inputAddress2" class="form-label">Region o Estado</label>
                            {{form.region}}
                        </div>
                        <div class="col-md-4">
                            <label for="inputCity" class="form-label">City</label>
                            {{form.city}}
                        </div>
                        <div class="col-md-4">
                            <label for="inputState" class="form-label">Celular</label>
                            {{form.phone}}
                        </div>
                        <div class="col-md-4">
                            <label for="inputZip" class="form-label">Contrasena</label>
                            {{form.password}}
                        </div>
                        <div class="col-12">
                            {{form.captcha}}
                        </div>
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary">Registrarse</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</section>

{% include 'includes/footer.html' %}
{% endblock content %}