eventeam/applications/home/urls.py
from django.urls import path

from . import views


app_name = "home_app"


urlpatterns = [
    path(
        '',
        views.HomeView.as_view(),
        name='inicio'),
]

eventeam/applications/salones/urls.py
from django.urls import path

from . import views


app_name = "salones_app"


urlpatterns = [
    path(
        'salones-de-eventos/',
        views.ListaSalonesView.as_view(),
        name='lista-eventos'),
    path(
        'salon-evento/<pk>/',
        views.SalonView.as_view(),
        name='salon-evento'),
    path(
        'reservar-salon/<pk>/',
        views.ReservarSalonView.as_view(),
        name='reservar'),
    path(
        'registrar-salon/',
        views.RegistrarSalon.as_view(),
        name='registrar-salon'),
    path(
        'update-salon/<pk>/',
        views.UpdateSalon.as_view(),
        name='update-salon'),
    path(
        'upload-image/<pk>/',
        views.UploadImage.as_view(),
        name='upload-image'),
    path(
        'update-salon/<pk_alt>/delete-image/<pk>/',
        views.EliminarImagen.as_view(),
        name='delete-image'),
    path(
        'propietarios/mis-salones/',
        views.MisSalonesView.as_view(),
        name='mis-salones'),
    path(
        'propietarios/mis-salones/<pk>',
        views.DeleteSalon.as_view(),
        name='delete-salon'),
    path(
        'propietarios/lista-reservas/',
        views.ReservasPropietarioListView.as_view(),
        name='lista-reservas'),

]

eventeam/applications/users/urls.py
from django.urls import path

from . import views
from .views import ResetPasswordView
from django.contrib.auth import views as auth_views
app_name = "users_app"


urlpatterns = [
    path(
        'registrar/',
        views.UserRegisterView.as_view(),
        name='user-register'),
    path(
        'login/',
        views.LoginUser.as_view(),
        name='user-login'),
    path(
        'logout/',
        views.LogoutView.as_view(),
        name='user-logout'),
    path(
        'registrar-propietario/',
        views.PropietarioRegister.as_view(),
        name='registrar-propietario'),
    path(
        'password-reset/',
         ResetPasswordView.as_view(),
        name='password_reset'),

]

eventeam/eventeam/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.salones.urls')),
    re_path('', include('applications.users.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventeam/applications/home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'home/index.html'

eventeam/templates/home/index.html
{% extends 'base.html' %}
{% block title %}

Salones de eventos
{% endblock title%}
{% block description%}<meta name="description" content="El mejor organizador de eventos. Registrate y encuentra, entre varias
opciones, lo que mejor se acomode para tus fiestas y reuniones.">{% endblock description%}
{% block content %}
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="/eventeam/static">Eventeam</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto my-2 my-lg-0">

                {% if not user.is_anonymous %}


                {% if user.type == 1%}
                <li class="nav-item"><a class="nav-link" href="{% url 'salones_app:lista-eventos'%}">Salones de
                    eventos</a></li>
                {% else%}
                <li class="nav-item"><a class="nav-link" href="{% url 'salones_app:mis-salones' %}">Mis salones</a></li>
                {% endif %}
                <li class="nav-item"><a class="nav-link" href="{% url 'users_app:user-logout' %}">Cerrar sesión</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'users_app:user-login' %}">Iniciar sesión</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'users_app:registrar-propietario' %}">¿Eres
                    propietario de salones?</a></li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>
<!-- Masthead-->
<header class="masthead">
    <div class="container px-4 px-lg-5 h-100">
        <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-8 align-self-end">
                <h1 class="text-white font-weight-bold">La mejor agenda para eventos sociales</h1>
                <hr class="divider"/>
            </div>
            <div class="col-lg-8 align-self-baseline">
                <p class="text-white-75 mb-5">El mejor organizador online para tus eventos sociales. Busca locales de
                    eventos disponibles y agéndalos</p>
                <a class="btn btn-primary btn-xl" href="#about">Conocer más</a>
            </div>
        </div>
    </div>
</header>
<!-- About-->
<section class="page-section color-propio" id="about">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="text-white mt-0">¿Buscas un lugar para tus eventos?</h2>
                <hr class="divider divider-light"/>
                <p class="text-white-75 mb-4">Ya sea que estés planeando una boda, una conferencia, una fiesta de cumpleaños o cualquier otro tipo de evento, entendemos lo importante que es encontrar el lugar adecuado. Con nuestra plataforma intuitiva, podrás explorar una variedad de opciones en tu área, filtrar por capacidad, ubicación y servicios adicionales para satisfacer tus necesidades y preferencias específicas.</p>
                <a class="btn btn-light btn-xl" href="#services">Iniciar</a>
            </div>
        </div>
    </div>
</section>
<!-- Services-->
<section class="page-section" id="services">
    <div class="container px-4 px-lg-5">
        <h2 class="text-center mt-0">A tú servicio</h2>
        <hr class="divider"/>
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-3 col-md-6 text-center">
                <div class="mt-5">
                            <span class="fa-stack fa-4x">
                                <i class="fas fa-circle fa-stack-2x text-primary"></i>
                                <i class="fa-solid fa-magnifying-glass fa-stack-1x fa-inverse"></i>
                            </span>
                    <h3 class="h4 mb-2 mt-2">Encuentra lo que buscas</h3>
                    <p class="text-muted mb-0">Puedes buscar un salón de eventos que se ajuste a tí.</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="mt-5">
                            <span class="fa-stack fa-4x">
                                <i class="fas fa-circle fa-stack-2x text-primary"></i>
                                <i class="fa-solid fa-filter fa-stack-1x fa-inverse"></i>
                            </span>
                    <h3 class="h4 mb-2 mt-2">Filtra a tu preferencia</h3>
                    <p class="text-muted mb-0">Con los diferente filtros, puedes encontrar rápidamente-</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="mt-5">
                            <span class="fa-stack fa-4x">
                                <i class="fas fa-circle fa-stack-2x text-primary"></i>
                                <i class="fa-solid fa-calendar-days fa-stack-1x fa-inverse"></i>
                            </span>
                    <h3 class="h4 mb-2 mt-2">Agenda tu evento</h3>
                    <p class="text-muted mb-0">Utiliza nuestro sitio para agendar tu evento.</p>
                </div>
            </div>

        </div>
    </div>
</section>

<!-- Call to action-->
<section class="page-section bg-dark text-white">
    <div class="container px-4 px-lg-5 text-center">
        <h2 class="mb-4">Inicia ya!</h2>
        {% if not user.is_anonymous %}


        {% if user.type == 1%}
        <a class="btn btn-light btn-xl" href="{% url 'salones_app:lista-eventos'%}">Buscar salones</a>
        {% else%}
        <a class="btn btn-light btn-xl" href="{% url 'salones_app:mis-salones'%}">Ver mis salones</a>
        {% endif %}
        {% else %}
        <a class="btn btn-light btn-xl" href="login/">Iniciar tu evento</a>
        {% endif %}
    </div>
</section>
<!-- Contact-->

{% include 'includes/footer.html' %}
{% endblock content %}