eventeam/applications/salones/urls.py
from django.urls import path

from . import views


app_name = "salones_app"


urlpatterns = [
    path(
        'salones-de-eventos/',
        views.ListaSalonesView.as_view(),
        name='lista-eventos'),
    path(
        'salon-evento/<pk>/',
        views.SalonView.as_view(),
        name='salon-evento'),
    path(
        'reservar-salon/<pk>/',
        views.ReservarSalonView.as_view(),
        name='reservar'),
    path(
        'registrar-salon/',
        views.RegistrarSalon.as_view(),
        name='registrar-salon'),
    path(
        'update-salon/<pk>/',
        views.UpdateSalon.as_view(),
        name='update-salon'),
    path(
        'upload-image/<pk>/',
        views.UploadImage.as_view(),
        name='upload-image'),
    path(
        'update-salon/<pk_alt>/delete-image/<pk>/',
        views.EliminarImagen.as_view(),
        name='delete-image'),
    path(
        'propietarios/mis-salones/',
        views.MisSalonesView.as_view(),
        name='mis-salones'),
    path(
        'propietarios/mis-salones/<pk>',
        views.DeleteSalon.as_view(),
        name='delete-salon'),
    path(
        'propietarios/lista-reservas/',
        views.ReservasPropietarioListView.as_view(),
        name='lista-reservas'),

]

eventeam/applications/users/urls.py
from django.urls import path

from . import views
from .views import ResetPasswordView
from django.contrib.auth import views as auth_views
app_name = "users_app"


urlpatterns = [
    path(
        'registrar/',
        views.UserRegisterView.as_view(),
        name='user-register'),
    path(
        'login/',
        views.LoginUser.as_view(),
        name='user-login'),
    path(
        'logout/',
        views.LogoutView.as_view(),
        name='user-logout'),
    path(
        'registrar-propietario/',
        views.PropietarioRegister.as_view(),
        name='registrar-propietario'),
    path(
        'password-reset/',
         ResetPasswordView.as_view(),
        name='password_reset'),

]

eventeam/eventeam/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.salones.urls')),
    re_path('', include('applications.users.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventeam/applications/salones/models.py
from django.db import models

from ..users.models import User


class Tags(models.Model):
    nombre = models.CharField(verbose_name='Nombre del tag', max_length=100)

    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

    def __str__(self):
        return self.nombre


class Espacio(models.Model):
    nombre = models.CharField(verbose_name='Nombre del espacio', max_length=100)

    class Meta:
        verbose_name = 'Espacio'
        verbose_name_plural = 'Espacio'

    def __str__(self):
        return self.nombre


class Salon(models.Model):
    class Rango(models.IntegerChoices):
        DIEZ_CINCUENTA = (1, 'De 10 a 50')
        CINCUENTA_CIEN = (2, 'De 50 a 100')
        CIEN_QUINIENTOS = (3, 'De 100 a 500')
        QUINIENTOS_MIL = (4, 'De 500 a 1000')
        MAS = (5, 'Mas de 1000')

    nombre = models.CharField(verbose_name='Nombre del salon', max_length=50, unique=True)
    ciudad = models.CharField(verbose_name='Ciudad', max_length=50)
    region = models.CharField(verbose_name='Region', max_length=100)
    direccion = models.CharField(verbose_name='Direccion', max_length=100)
    description = models.CharField(verbose_name='Descripcion', max_length=200)
    alquiler = models.DecimalField(verbose_name='Alquiler', decimal_places=3, max_digits=7)
    rango = models.IntegerField(verbose_name='Rango', choices=Rango.choices)
    tags = models.ManyToManyField(Tags)
    espacios = models.ManyToManyField(Espacio)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Salon'
        verbose_name_plural = 'Salones'

    def __str__(self):
        return self.nombre


class SalonImages(models.Model):
    image = models.ImageField(blank=False, null=False, upload_to='salones/')
    salon = models.ForeignKey(Salon, on_delete=models.CASCADE, related_name='imagenes')

    class Meta:
        verbose_name = 'Imagen del salon'
        verbose_name_plural = 'Imagenes del salon'

    def __str__(self):
        return 'imagen del salon %s' % self.salon.nombre


class ReservaSalon(models.Model):
    class Aprox(models.IntegerChoices):
        DIEZ_CINCUENTA = (1, '0-100')
        CINCUENTA_CIEN = (2, '100-200')
        CIEN_QUINIENTOS = (3, '200 o más')

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reservas')
    salon = models.ForeignKey(Salon, on_delete=models.CASCADE, related_name='reservas')
    inv_aprox = models.IntegerField(verbose_name='Invitados aproximados', choices=Aprox.choices)
    fecha = models.DateField(verbose_name='fecha')
    created_at = models.DateField(verbose_name='Creado el', auto_now_add=True)

eventeam/applications/salones/forms.py
from django import forms
from .models import Salon, Tags, SalonImages, ReservaSalon


class SalonForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = visible.field.label
    class Meta:
        exclude = ['user']
        model = Salon
        widgets = {
            'description': forms.Textarea(attrs={'rows': 3}),
        }


class ImageForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = visible.field.label

    class Meta:
        model = SalonImages
        fields = ['image']


class ReservarForm(forms.ModelForm):
    fecha = forms.DateField(widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'date'}))

    class Meta:
        model = ReservaSalon
        fields = ['fecha', 'inv_aprox']
        widgets = {
            'inv_aprox': forms.Select(
                attrs={
                    'class': 'form-select'
                }
            )

        }

eventeam/applications/salones/views.py
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import TemplateView, FormView, CreateView, UpdateView, ListView, DeleteView, DetailView
from .forms import SalonForm, ImageForm, ReservarForm
from django.template.loader import get_template
from django.forms.models import inlineformset_factory
from django.conf import settings
from .models import Salon, SalonImages, ReservaSalon
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core.mail import EmailMessage

class ListaSalonesView(ListView):
    template_name = 'salones/lista-salones.html'
    ordering = 'id'
    model = Salon
    paginate_by = 5
    context_object_name = 'lista'

    def get_queryset(self):
        palabra_clave = self.request.GET.get('kword', '')
        print(palabra_clave)
        if palabra_clave == '':
            queryset = Salon.objects.all()
        else:
            queryset = Salon.objects.filter(
                nombre=palabra_clave
            )
        ordering = self.get_ordering()
        if ordering:
            if isinstance(ordering, str):
                ordering = (ordering,)
            queryset = queryset.order_by(*ordering)
        return queryset


class SalonView(DetailView):
    template_name = 'salones/salon-evento.html'
    model = Salon

    def get_context_data(self, **kwargs):
        contexto = super(SalonView, self).get_context_data(**kwargs)
        contexto['reserva'] = ReservarForm
        return contexto


class ReservarSalonView(View):

    def post(self, request, *args, **kwargs):
        form = ReservarForm(request.POST)
        id_salon = self.kwargs['pk']
        salon = Salon.objects.get(id=id_salon)
        if form.is_valid():
            fecha = form.cleaned_data['fecha']
            inv_aprox = form.cleaned_data['inv_aprox']
            ReservaSalon.objects.create(
                fecha=fecha,
                inv_aprox=inv_aprox,
                user=request.user,
                salon=salon

            )
            ctx = {
                'nombre': request.user.first_name + ' ' + request.user.last_name,
                'telefono': request.user.phone,
                'email': request.user.email,
                'fecha': fecha,
                'inv_aprox': inv_aprox
            }
            message = get_template('salones/notificacion-reserva.html').render(ctx)
            msg = EmailMessage(
                'Nueva reserva',
                message,
                settings.EMAIL_HOST_USER,
                [salon.user.email],
            )
            msg.content_subtype = "html"  # Main content is now text/html
            msg.send()

        return HttpResponseRedirect(
            reverse(
                'salones_app:lista-eventos',
            )
        )


class RegistrarSalon(FormView):
    template_name = 'salones/registrar-salon.html'
    model = Salon
    form_class = SalonForm
    success_url = reverse_lazy('salones_app:mis-salones')

    def form_valid(self, form):
        tags = form.cleaned_data.pop('tags')
        espacios = form.cleaned_data.pop('espacios')
        salon = Salon.objects.create(
            **form.cleaned_data,
            user=self.request.user
        )
        salon.tags.set(tags)
        salon.espacios.set(espacios)
        return super(RegistrarSalon, self).form_valid(form)


class UpdateSalon(UpdateView):
    template_name = 'salones/actualizar-salon.html'
    model = Salon
    form_class = SalonForm
    success_url = reverse_lazy('salones_app:update-salon')

    def get_context_data(self, **kwargs):
        context = super(UpdateSalon, self).get_context_data(**kwargs)
        context['form_image'] = ImageForm
        return context

    def get_success_url(self):
        return reverse_lazy('salones_app:salon-evento', kwargs={'pk': self.get_object().id})


class UploadImage(View):

    def post(self, request, *args, **kwargs):
        id_salon = self.kwargs['pk']
        image = request.FILES['image']
        salon = Salon.objects.get(id=id_salon)
        SalonImages.objects.create(
            image=image,
            salon=salon
        )
        return HttpResponseRedirect(
            reverse(
                'salones_app:update-salon', kwargs={'pk': id_salon},
            )
        )


class EliminarImagen(DeleteView):
    model = SalonImages

    def get_success_url(self, **kwargs):
        id_salon = self.kwargs['pk_alt']
        return reverse('salones_app:update-salon', kwargs={'pk': id_salon})


class MisSalonesView(ListView):
    template_name = 'salones/mis-salones.html'
    model = Salon
    paginate_by = 5
    fields = '__all__'
    context_object_name = 'lista'
    ordering = 'id'

    def get_queryset(self):
        queryset = Salon.objects.filter(
            user=self.request.user
        )
        ordering = self.get_ordering()
        if ordering:
            if isinstance(ordering, str):
                ordering = (ordering,)
            queryset = queryset.order_by(*ordering)
        return queryset


class DeleteSalon(DeleteView):
    model = Salon
    success_url = reverse_lazy('salones_app:mis-salones')


class ReservasPropietarioListView(ListView):
    model = ReservaSalon
    ordering = 'created_at'
    template_name = 'salones/lista-reservas.html'
    paginate_by = 10
    context_object_name = 'lista'

    def get_queryset(self):
        primer_queryset = Salon.objects.filter(user=self.request.user)
        queryset = ReservaSalon.objects.filter(salon__in=primer_queryset)
        ordering = self.get_ordering()
        if ordering:
            if isinstance(ordering, str):
                ordering = (ordering,)
            queryset = queryset.order_by(*ordering)
        return queryset

eventeam/templates/salones/actualizar-salon.html
{% extends 'base.html' %}
{% block title %}
Salones de eventos
{% endblock title%}
{% block content %}
{% include 'includes/header.html' %}
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <div id="carouselExampleControls" class="carousel slide shadow" data-bs-ride="carousel">
                <div class="carousel-inner rounded">
                    {% for i in object.imagenes.all %}
                    <div class="carousel-item active" style="height: 70vh;">
                        <img src="{{i.image.url}}" style="height: 100%; object-fit: cover;" class="d-block w-100"
                             alt="...">
                        <div class="carousel-caption d-none d-md-block  mt-5">
                            <form method="POST" action="{% url 'salones_app:delete-image' object.id i.id %}"> {% csrf_token %}
                                <button type="submit" class="btn btn-primary ">Eliminar imagen</button>
                            </form>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls"
                        data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls"
                        data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
        <div class="col-sm-6">
            <h3>Subir imágen del salón de eventos</h3>
            <form method="POST" action="{% url 'salones_app:upload-image' object.id  %}" enctype="multipart/form-data">{% csrf_token %}

                {{form_image.image}}
                <button type="submit" class="btn btn-primary mt-3">Subir imagen</button>

            </form>
        </div>

    </div>
</div>

<form method="POST">{% csrf_token %}
    <div class="container p-5">
        <div class="card">
            <div class="card-body p-5">
                <h5 class="card-title">Card title</h5>
                <div class="card-body">
                    <div class="row "> {% csrf_token %}
                        <div class="col-sm-4">
                            <label for="inputEmail4" class="form-label">Nombre</label>
                            {{form.nombre}}
                        </div>
                        <div class="col-sm-4">
                            <label for="inputPassword4" class="form-label">Ciudad</label>
                            {{form.ciudad}}
                        </div>
                        <div class="col-md-4">
                            <label for="inputAddress" class="form-label">Region o estado</label>
                            {{form.region}}
                        </div>
                        <div class="col-md-6">
                            <label for="inputAddress2" class="form-label">Region o Estado</label>
                            {{form.direccion}}
                        </div>
                        <div class="col-md-2">
                            <label for="inputCity" class="form-label">Alquiler</label>
                            {{form.alquiler}}
                        </div>
                        <div class="col-md-4">
                            <label for="inputState" class="form-label">Rango de personas</label>
                            {{form.rango}}
                        </div>
                        <div class="col-md-12">
                            <label for="inputZip" class="form-label">Contrasena</label>
                            {{form.description}}
                        </div>
                        <div class="col-12">
                            <label for="inputZip" class="form-label">Tags</label>
                            {{form.tags}}
                        </div>
                        <div class="col-12">
                            <label for="inputZip" class="form-label">Espacios</label>
                            {{form.espacios}}
                        </div>
                        <div class="col-12 mt-3">
                            <button type="submit" class="btn btn-primary">Actualizar</button>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<div class="container">
 <div class="col-12 mt-3">
     <form method="POST" action="{% url 'salones_app:delete-salon' object.id%}">{% csrf_token %}
     <button type="submit" class="btn btn-danger">Eliminar</button>
    </form>
 </div>
</div>
{% include 'includes/footer.html' %}
{% endblock content %}

eventeam/templates/salones/lista-reservas.html
{% extends 'base.html' %}
{% block title %}
Salones de eventos
{% endblock title%}
{% block content %}
{% include 'includes/header.html' %}
{{lista}}
{% include 'includes/footer.html' %}
{% endblock content %}

eventeam/templates/salones/mis-salones.html
{% extends 'base.html' %}
{% block title %}
    Salones de eventos
{% endblock title%}
{% block content %}
{% include 'includes/header.html' %}

    <div class="container m-4"><h1>Mis eventos</h1></div>
    <div class="container ">
        <a href="{% url 'salones_app:registrar-salon'%}" class="btn btn-primary">Agregar salon</a>
    </div>
    <div class="container mt-1">

    {% for e in lista %}
    <div class="card mb-3 border-start-0 border-end-0 border-top-0 py-3">
        <div class="row g-0">
            <div class="col-md-3">
                <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">

                    <div class="carousel-inner rounded">
                        {% for i in e.imagenes.all %}
                        <div class="carousel-item active" style="height: 200px;">
                            <img src="{{i.image.url}}"
                                 style="height: 100%; object-fit: cover;" class="d-block w-100"
                                 alt="Imagenes no encontradas">
                        </div>
                        {% endfor %}
                    </div>
                    <button class="carousel-control-prev" type="button"
                            data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button"
                            data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>


            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{e.nombre}}</h5>
                    <p class="card-text"><small class="text-muted"><i class="fa-solid fa-users"></i>
                        {{e.get_rango_display}} personas</small></p>
                    <p class="card-text">{{e.description}}</p>
                    <div class="row">
                        <div class="col-lg-9">
                            <p class="card-text"><small class="text-muted"><i
                                    class="fa-solid fa-location-dot"></i> {{e.ciudad}}, {{e.region}}</small></p>
                        </div>
                        <div class="col-lg-3">
                            <a href="{% url 'salones_app:salon-evento' e.id %}">Ver o actualizar -></a>
                        </div>

                    </div>


                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% if is_paginated%}

    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Previous</a></li>
        {% endif %}
        {% for pagina in paginator.page_range %}
        {% if pagina == page_obj.number %}
        <li class="page-item"><a class="page-link active" href="#">{{pagina}}</a></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page={{pagina}}">{{pagina}}</a></li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next%}
        <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a></li>
        {% endif %}
    </ul>

    {% endif %}
</div>

    {% include 'includes/footer.html' %}
{% endblock content %}

eventeam/templates/salones/notificacion-reserva.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Notificacion reserva</title>
</head>
<body>
<h2>Notifiación sobre solicitud de reservación</h2>
<p>Se registró una nueva solicitud para una reservación a su salón de eventos.
    Nombre: {{nombre}}
    Telefono: {{telefono}}
    Email: {{email}}
    Fecha: {{fecha}}
    inv_aprox:{{inv_aprox}}
</p>

Eventeam
</body>
</html>

eventeam/templates/salones/registrar-salon.html
{% extends 'base.html' %}
{% block title %}
Salones de eventos
{% endblock title%}
{% block content %}
{% include 'includes/header.html' %}
<form method="POST">{% csrf_token %}
    <div class="container p-5">
        <div class="card">
            <div class="card-body p-5">
                <h5 class="card-title">Card title</h5>
                <div class="card-body">
                <div class="row "> {% csrf_token %}
                        <div class="col-sm-4">
                            <label for="inputEmail4" class="form-label">Nombre</label>
                            {{form.nombre}}
                        </div>
                        <div class="col-sm-4">
                            <label for="inputPassword4" class="form-label">Ciudad</label>
                            {{form.ciudad}}
                        </div>
                        <div class="col-md-4">
                            <label for="inputAddress" class="form-label">Region o estado</label>
                            {{form.region}}
                        </div>
                        <div class="col-md-6">
                            <label for="inputAddress2" class="form-label">Region o Estado</label>
                            {{form.direccion}}
                        </div>
                        <div class="col-md-2">
                            <label for="inputCity" class="form-label">Alquiler</label>
                            {{form.alquiler}}
                        </div>
                        <div class="col-md-4">
                            <label for="inputState" class="form-label">Rango de personas</label>
                            {{form.rango}}
                        </div>
                        <div class="col-md-12">
                            <label for="inputZip" class="form-label">Descripción</label>
                            {{form.description}}
                        </div>
                        <div class="col-12">
                            <label for="inputZip" class="form-label">Tags</label>
                            {{form.tags}}
                        </div>
                        <div class="col-12">
                            <label for="inputZip" class="form-label">Espacios</label>
                            {{form.espacios}}
                        </div>
                        <div class="col-12 mt-3">
                            <button type="submit" class="btn btn-primary">Agregar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% include 'includes/footer.html' %}
{% endblock content %}

eventeam/templates/salones/salon-evento.html
{% extends 'base.html' %}
{% block title %}
Salones de eventos
{% endblock title%}
{% block content %}
{% include 'includes/header.html' %}

<div class="container">

    <div class="row">
        <div class="col-sm-4">

            <h2>Salon de evento {{object.nombre}}</h2>
            <div class="container mb-3">
                <div class="row">
                    <div class="col">

                        <div class="col">
                            <small>Para eventos :</small>
                            {% for t in object.tags.all %}
                            <span class="badge rounded-pill bg-primary"><a href="#" class="link-light">{{t.nombre}}</a></span>
                            {% endfor %}
                        </div>
                    </div>
                </div>

            </div>
            <div class="card shadow">
                <div class="card-body">
                    <div class="card shadow my-4">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item"><h6 class="card-subtitle p-2 text-primary "><i
                                    class="fa-solid fa-location-dot me-2"></i>{{object.ciudad}}, {{object.region}}</h6>
                            </li>
                            <li class="list-group-item"><h6 class="card-subtitle p-2 text-primary"><i
                                    class="fa-solid fa-wallet me-2"></i></i>
                                {{object.alquiler}}$</h6></li>
                            <li class="list-group-item"><h6 class="card-subtitle p-2 text-primary"><i
                                    class="fa-solid fa-users me-2"></i>{{object.get_rango_display}} personas</h6></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="container mt-3">
                <div class="row">
                    {% if not user.is_anonymous %}


                    {% if user.type == 1%}
                    <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Enviar petición de reservación
                    </button>
                    {% else%}
                    {% if user.id == object.user.id%}
                    <a href="{% url 'salones_app:update-salon' object.id %}" class="btn btn-primary">Actualizar el salon</a>
                    {% endif %}
                    {% endif %}
                    {% else %}
                    <form method="GET" action="{% url 'users_app:user-login'%}">
                        <button class="btn btn-primary" href="login/">Inicia sesión para reservar</button>
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-sm-8">
            <div id="carouselExampleControls" class="carousel slide shadow" data-bs-ride="carousel">
                <div class="carousel-inner rounded">
                    {% for i in object.imagenes.all %}
                    <div class="carousel-item active" style="height: 70vh;">
                        <img src="{{i.image.url}}" style="height: 100%; object-fit: cover;" class="d-block w-100"
                             alt="...">
                    </div>
                    {% endfor %}
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls"
                        data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls"
                        data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
        <div class="card shadow mt-2 text-center">
            <div class="card-body">
                <h5 class="card-title">Descripción general</h5>
                {{object.description}}
            </div>
        </div>

    </div>
</div>
<div class="container mt-5">
    <h3>Espaacios</h3>
    <ul>
        <li>sdasda</li>
        <li>sdasda</li>
        <li>sdasda</li>
    </ul>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Enviar solicitud de reservación</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <small class="card-text text-muted">
                    Ingresa los datos para la reservación del salon de eventos {{object.nombre}}. Después
                    de un tiempo, se pondrán en contacto contigo.
                </small>
                <form method="POST" action="{% url 'salones_app:reservar' object.id %}"> {% csrf_token %}
                    <div class="mt-3">
                        <label for="startDate" class="mb-2">Fecha del evento</label>
                        {{ reserva.fecha }}
                    </div>
                    <div class="mt-3">
                        <label class="mb-2">Selecciona el estimado de invitados</label>
                        {{ reserva.inv_aprox }}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                        <button type="input" class="btn btn-primary">Hacer la reserva</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>
{% include 'includes/footer.html' %}

{% endblock content %}